"""Read FLAGS_JSON from env and overwrite flag locations in the container.

This script is executed at container startup (via inject-flags.sh) to replace
build-time placeholder flags with unique per-instance values generated by
the platform's flag_generator service.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path


def _replace_in_file(path: Path, patterns: list[str], replacement: str) -> None:
    """Replace all matching patterns in a file with the replacement string."""
    if not path.exists():
        return
    text = path.read_text()
    for pattern in patterns:
        text = re.sub(pattern, replacement, text)
    path.write_text(text)


def inject_flags() -> None:
    """Main injection logic driven by the FLAGS_JSON environment variable."""
    raw = os.environ.get("FLAGS_JSON", "")
    if not raw:
        return

    flags: dict[str, str] = json.loads(raw)

    # Chall 1: replace flag in server.py
    if "NBL01" in flags:
        _replace_in_file(
            Path("/opt/chall1/server.py"),
            [r"NBL01\{[^}]*\}", r"INF01\{[^}]*\}"],
            flags["NBL01"],
        )

    # Chall 2: replace TXT record in BIND zone files
    if "NBL02" in flags:
        zones_dir = Path("/etc/bind/zones")
        if zones_dir.exists():
            for zone_file in zones_dir.glob("db.unk.*"):
                _replace_in_file(
                    zone_file,
                    [r"NBL02\{[^}]*\}", r"INF02\{[^}]*\}"],
                    flags["NBL02"],
                )

    # Chall 3-7: simple file replacements
    flag_files: dict[str, str] = {
        "NBL03": "/opt/chall3/tinyfilemanager/infinity.txt",
        "NBL04": "/home/taylor/user.txt",
        "NBL05": "/opt/chall5/flag.txt",
        "NBL06": "/home/john/flag.txt",
        "NBL07": "/root/root.txt",
    }
    for prefix, path_str in flag_files.items():
        if prefix not in flags:
            continue
        target = Path(path_str)
        if target.parent.exists():
            target.write_text(flags[prefix] + "\n")


if __name__ == "__main__":
    inject_flags()
