[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/run/supervisord.pid

[program:chall1]
command=/usr/bin/python3 -u /opt/chall1/server.py
directory=/opt/chall1
autostart=true
autorestart=true
stdout_logfile=/var/log/infinity/chall1.log
stderr_logfile=/var/log/infinity/chall1.err.log

[program:named]
command=/usr/sbin/named -g -c /etc/bind/named.conf
autostart=true
autorestart=true
stdout_logfile=/var/log/infinity/named.log
stderr_logfile=/var/log/infinity/named.err.log

[program:tinyfilemanager]
command=/usr/bin/php -S 127.0.0.1:8081 -t /opt/chall3/tinyfilemanager
directory=/opt/chall3/tinyfilemanager
autostart=true
autorestart=true
stdout_logfile=/var/log/infinity/tinyfilemanager.log
stderr_logfile=/var/log/infinity/tinyfilemanager.err.log

[program:nginx]
command=/bin/bash -lc "/usr/sbin/nginx -g 'daemon off;'"
autostart=true
autorestart=true
stdout_logfile=/var/log/infinity/nginx.log
stderr_logfile=/var/log/infinity/nginx.err.log

[program:chall5]
command=/usr/bin/python3 /opt/chall5/server.py
directory=/opt/chall5
user=brown
autostart=true
autorestart=true
stdout_logfile=/var/log/infinity/chall5.log
stderr_logfile=/var/log/infinity/chall5.err.log
